### ISSUE TITLE
Catalog Builder Tool -'src' not found

### ISSUE THREAD

**Issue by nishsilva** [NOAA-GFDL/MDTF-diagnostics#562]
I am trying to use the catalog builder tool in the MDTF framework to generate a data catalog for a 4th generation POD. When I run the tool following the instructions it returns a` ModuleNotFoundError `indicating that 'src' module is not available. 

I confirmed that the directory have the expected structure to call 'src'. 

Could someone take a look into this?

Thanks,
Nish

```
> (_MDTF_base) netige@crhtc53:/glade/work/netige/mdtf_Apr24_2/mdtf/MDTF-diagnostics/tools/catalog_builder> python3 catalog_builder.py --config zos_builder_config.yml
> Traceback (most recent call last):
>   File "/glade/work/netige/mdtf_Apr24_2/mdtf/MDTF-diagnostics/tools/catalog_builder/catalog_builder.py", line 25, in <module>
>     from src.util import json_utils, basic
> ModuleNotFoundError: No module named 'src' 
```

**Comment by wrongkindofdoctor** [comment]
@nishsilva The import issue should be fixed. Please merge the main branch updates into your fork and try the catalog builder again.

**Comment by nishsilva** [comment]
@wrongkindofdoctor I updated the fork and tried the catalog builder after pulling the updates. But the issue still exists for me.

```

> (_MDTF_base) netige@crhtc53:/glade/work/netige/mdtf_Apr24_2/mdtf/MDTF-diagnostics/tools/catalog_builder> python3 catalog_builder.py --config /glade/work/netige/mdtf_Apr24_2/data_catalogs/zos_builder_config.yml 
> Traceback (most recent call last):
>   File "/glade/work/netige/mdtf_Apr24_2/mdtf/MDTF-diagnostics/tools/catalog_builder/catalog_builder.py", line 34, in <module>
>     from src import util
> ModuleNotFoundError: No module named 'src'

```

**Comment by wrongkindofdoctor** [comment]
@nishsilva As a workaround, try commenting out the line. Only the GFDL builder needs the util modules at this time.

**Comment by nishsilva** [comment]
@wrongkindofdoctor Thank you for this, Jess. This worked out! Closing the issue.
